# Generated by Django 5.2.17 on 2026-10-01 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='商品名')),
                ('description', models.TextField(blank=True, verbose_name='商品説明')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='価格 (円)')),
                ('stock', models.PositiveIntegerField(default=10, verbose_name='在庫数')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='商品画像')),
                ('is_active', models.BooleanField(default=True, verbose_name='公開状態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品一覧',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='タグ名')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='スラグ')),
                ('color', models.CharField(choices=[('primary', 'Primary (Blue)'), ('secondary', 'Secondary (Gray)'), ('success', 'Success (Green)'), ('danger', 'Danger (Red)'), ('warning', 'Warning (Yellow)'), ('info', 'Info (Teal)'), ('dark', 'Dark (Black)')], default='primary', max_length=20, verbose_name='バッジ色')),
            ],
            options={
                'verbose_name': 'タグ',
                'verbose_name_plural': 'タグ一覧',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=32, unique=True, verbose_name='注文番号')),
                ('full_name', models.CharField(max_length=100, verbose_name='氏名')),
                ('postal_code', models.CharField(max_length=10, verbose_name='郵便番号')),
                ('address', models.CharField(max_length=255, verbose_name='配送先住所')),
                ('phone_number', models.CharField(max_length=20, verbose_name='電話番号')),
                ('email', models.EmailField(max_length=254, verbose_name='メールアドレス')),
                ('payment_method', models.CharField(choices=[('credit_card', 'クレジットカード決済'), ('bank_transfer', '銀行振込'), ('cod', '代金引換'), ('convenience', 'コンビニ決済')], default='credit_card', max_length=20, verbose_name='支払方法')),
                ('total_price', models.PositiveIntegerField(default=0, verbose_name='合計金額 (円)')),
                ('status', models.CharField(choices=[('pending', '処理待ち'), ('processing', '発送準備中'), ('shipped', '発送済み'), ('completed', '配達完了'), ('cancelled', 'キャンセル')], default='completed', max_length=20, verbose_name='注文ステータス')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='注文日時')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='購入ユーザー')),
            ],
            options={
                'verbose_name': '注文',
                'verbose_name_plural': '注文履歴',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='購入時商品名')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='購入時単価')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='数量')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.order', verbose_name='注文')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '注文明細',
                'verbose_name_plural': '注文明細一覧',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='products', to='shop.tag', verbose_name='タグ'),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='shop.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': 'お気に入り',
                'verbose_name_plural': 'お気に入り一覧',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'product')},
            },
        ),
    ]
